### ISSUE TITLE
E badge

### ISSUE THREAD

**Issue by Djeshwin** [setar-nv/youthtechevent#2]
open pub sub client: no such file of dirrectory con mi por drecha esaki

**Comment by miceline** [comment]
Hi Just updated the README file.

You will need to install the following libraries to be able to compile the Badge Firmware.

PubSubClient by Nick O'Leary
ArduinoJson by Benoit Blanchon
U8g2 by oliver
TaskScheduler by Anatoli Arkhipenko

To install these simply click "sketch" on the Arduino IDE. Then "include library" -> and Manage Libraries. This will open the "Library Manager" dialog, here you will be able to filter by above mention library name. Once you find the correct library click the "install" button. This will download and install the library into the Arduino ide.

Let us know if you need further help.

**Comment by nathie1** [comment]
Mi tin problema cu 
Error opening serial port ‘COM4’ 
And ‘StaticJsonDocument’ was not declared in this scope 

Ki mi lo por haci?

**Comment by miceline** [comment]
> Mi tin problema cu
> Error opening serial port ‘COM4’
> And ‘StaticJsonDocument’ was not declared in this scope
> 
> Ki mi lo por haci?

@nathie1 
Hi if you are using Windows or Mac OSX please install the usb drivers from this website:
https://www.silabs.com/products/development-tools/software/usb-to-uart-bridge-vcp-drivers

"And ‘StaticJsonDocument’ was not declared in this scope"
Double check in the Arduino "Library Manager" if you installed version 6.9.0 or above. I believe the lastest version is 6.9.1.

I have attached a screenshot of the correct version:
![image](https://user-images.githubusercontent.com/832647/56101862-4f7bf400-5ef6-11e9-89bd-282b0e473123.png)
